### ISSUE TITLE
Project doesn't have a license yet.

### ISSUE THREAD

**Issue by arCABAL** [project-valhalla/main#21]
Could you add a license to the project? You mentioned in the past that you considered some open source licenses. I hope you can go through with this so that others can make derivatives of this project and have the right to republish those. If no license will be added, nobody will want to risk creating a fork and have their republishing rights removed from that if this project ever gets licensed restrictively with a non-free license. I'm not saying that this will happen, but the risk for them would still be there. Also, an open-source license will make others more likely to contribute directly to this project.

https://choosealicense.com/no-permission/
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by garsipal** [comment]
Source code is basically licensed under the permissive _zlib_ license, same as Cube 2 itself and most other Cube projects. This is stated in the `readme_valhalla_project.txt` file. We are not really scrapping the idea of switching to other compatible free licenses in the future but for now we are sticking to the current one. Though I understand that further clarifications regarding this matter are needed so a `LICENSE.md` file and other information will surely be added as the repository is updated. To further discuss licenses, please do not use **Issues**, use **Discussions** instead.
